### ISSUE TITLE
Chrome - Regression : 'Volume seek bar' is missing in volume slider on www.firstpost.com.

### ISSUE THREAD

**Issue by szhang96** [paceuniversity/cs3892017#45]
https://bugs.chromium.org/p/chromium/issues/detail?id=715063&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=200

**Comment by scharffc** [comment]
Again, why did you chose this bug?
